[package]
name = "cryptopanda"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dioxus={versin="0.2.4", features=["desktop","fermi", "router"]}
once_cell="1.13.0"